version: '3'
services:
  mysql-server:
    image: mysql:5.7
    container_name: mysql-server
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix.server
    volumes:
      - /data/zabbix/mysql:/var/lib/mysql                              
    networks:
      - zabbix-server-network
    command:
      --character-set-server=utf8
      --collation-server=utf8_bin

  zabbix-web-apache-mysql:
    build:
      context: ./zabbix-server
      dockerfile: Dockerfile
   # image: zabbix/zabbix-web-apache-mysql
    container_name: zabbix-web-apache-mysql
    environment:
      DB_SERVER_HOST: mysql-server
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix.server
      MYSQL_ROOT_PASSWORD: rootpassword
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: Asia/Shanghai
    ports:
      - 80:8080
    links:
      - mysql-server
      - zabbix-server
    depends_on:
      - mysql-server
      - zabbix-server                            
    networks:
      - zabbix-server-network

  zabbix-server:
    image: zabbix/zabbix-server-mysql
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: mysql-server
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix.server
      MYSQL_ROOT_PASSWORD: rootpassword
      ZBX_LOGTYPE: file
      ZBX_LOG_FILE: /tmp/ser.log 
    ports:
      - 10051:10051
    links:
      - mysql-server
    depends_on:
      - mysql-server                             
    networks:
      - zabbix-server-network

  zabbix-agent:
    image: zabbix/zabbix-agent
    container_name: zabbix-server-agent
    ports:
      - 10050:10050
    links:
      - zabbix-server:zabbix-server
    depends_on:
      - zabbix-server                             
    networks:
      - zabbix-server-network

networks:
    zabbix-server-network:
      driver: bridge
      ipam:
        driver: default
        config:
        - subnet: 172.16.100.0/24

